### PR TITLE
Patch decompiler

### PR DESCRIPTION
**Pull request by jhw**
So the idea here is to try and "decompile" an existing sunvox project into individual "patches" (like modular synthesis patches). You can then walk the different patches, see which ones you like, re- use/remix them. Not sure where it should go so have stuck in into `tools`. Code could probably do with some cleaning up. But a neat idea I think :-) Reminds me of Principal Component Analysis.

```
(radiant-voices) justin@justin-XPS-13-9360:~/work/radiant-voices$  mkdir tmp
(radiant-voices) justin@justin-XPS-13-9360:~/work/radiant-voices$ python rv/tools/patch_decompiler.py ~/packages/sunvox/examples/NightRadio\ -\ City\ Dreams.sunvox 
tmp/NightRadio - City Dreams/Gen-Loo-Del-Dis-0.sunvox
tmp/NightRadio - City Dreams/Gen-Loo-Del-Dis-0.sunvox
tmp/NightRadio - City Dreams/Kic-Dis-Dis-0.sunvox
tmp/NightRadio - City Dreams/FM-Ech-0.sunvox
tmp/NightRadio - City Dreams/Gen-Loo-Del-Dis-128.sunvox
tmp/NightRadio - City Dreams/Spe-Ech-128.sunvox
tmp/NightRadio - City Dreams/Gen-128.sunvox
tmp/NightRadio - City Dreams/Spe-Ech-192.sunvox
tmp/NightRadio - City Dreams/Spe-352.sunvox
tmp/NightRadio - City Dreams/Spe-384.sunvox
tmp/NightRadio - City Dreams/FM-Ech-384.sunvox
tmp/NightRadio - City Dreams/Gen-LFO-Fla-Ech-384.sunvox
tmp/NightRadio - City Dreams/Spe-Ech-384.sunvox
tmp/NightRadio - City Dreams/Gen-Loo-Del-Dis-416.sunvox
tmp/NightRadio - City Dreams/Gen-Loo-Del-Dis-416.sunvox
tmp/NightRadio - City Dreams/Kic-Dis-Dis-416.sunvox
tmp/NightRadio - City Dreams/FM-Fla-Ech-512.sunvox
tmp/NightRadio - City Dreams/Spe-Ech-512.sunvox
tmp/NightRadio - City Dreams/FM-Fla-Ech-576.sunvox
tmp/NightRadio - City Dreams/Gen-LFO-Fla-Ech-768.sunvox
tmp/NightRadio - City Dreams/Gen-Del-768.sunvox
tmp/NightRadio - City Dreams/Gen-Loo-Del-Dis-896.sunvox
tmp/NightRadio - City Dreams/Gen-Loo-Del-Dis-896.sunvox
tmp/NightRadio - City Dreams/Kic-Dis-Dis-896.sunvox
tmp/NightRadio - City Dreams/Spe-Ech-896.sunvox
tmp/NightRadio - City Dreams/Spe-Ech-960.sunvox
tmp/NightRadio - City Dreams/FM-Fla-Ech-1024.sunvox
tmp/NightRadio - City Dreams/FM-Fla-Ech-1088.sunvox
tmp/NightRadio - City Dreams/Gen-Loo-Del-Dis-1120.sunvox
tmp/NightRadio - City Dreams/Kic-Dis-Dis-1120.sunvox
tmp/NightRadio - City Dreams/Gen-1120.sunvox
tmp/NightRadio - City Dreams/Spe-1152.sunvox
tmp/NightRadio - City Dreams/Gen-Fla-Ech-1152.sunvox
tmp/NightRadio - City Dreams/FM-Ech-1152.sunvox
tmp/NightRadio - City Dreams/Gen-Fla-Ech-1184.sunvox
tmp/NightRadio - City Dreams/Spe-Ech-1664.sunvox
tmp/NightRadio - City Dreams/FM-Ech-1664.sunvox
tmp/NightRadio - City Dreams/Gen-Fil-Dis-Ech-1664.sunvox
tmp/NightRadio - City Dreams/Gen-Del-1664.sunvox
tmp/NightRadio - City Dreams/Gen-LFO-Fla-Ech-1792.sunvox
tmp/NightRadio - City Dreams/Spe-Ech-1920.sunvox
tmp/NightRadio - City Dreams/Gen-LFO-Fla-Ech-1920.sunvox
tmp/NightRadio - City Dreams/Spe-Ech-1984.sunvox
tmp/NightRadio - City Dreams/Gen-LFO-Fla-Ech-1984.sunvox
tmp/NightRadio - City Dreams/Spe-Ech-2048.sunvox
tmp/NightRadio - City Dreams/Spe-Ech-2112.sunvox
tmp/NightRadio - City Dreams/Gen-Loo-Del-Dis-2144.sunvox
tmp/NightRadio - City Dreams/Gen-Loo-Del-Dis-2144.sunvox
tmp/NightRadio - City Dreams/Kic-Dis-Dis-2144.sunvox
tmp/NightRadio - City Dreams/Gen-LFO-Fla-Ech-2304.sunvox
```

:-)

### CODE REVIEW

**Comment by gldnspud** [comment]
I haven't even looked at the code but I already like it based on the description and output file listing! Looking forward to digging in later and helping to push this one through. Let me know if there's anything specific you'd like me to review or help with.

**Comment by jhw** [comment]
There are a few edge cases the algo is getting wrong - some inaudible
patches due to bad module refs it seems - so will likely submit an updated
version in a few days. In the meantime you might like to opine on this one

https://github.com/metrasynth/radiant-voices/issues/27

as I it constantly trips me up and I think is probably a flaw. Other than
that I will leave it to u as to how you want to refactor and integrate the
code. But maybe wait for the update first. Meantime try it and see what u
think of the output

**Comment by jhw** [comment]
Latest and greatest version (final version for now) -

- cleans up a ton of edge cases that were leading to bad module references
- handles bad sample serialisation gracefully
- clones modules properly to retain stuff like colour
- handles loops in module chaining
- handles chords/polyphony
- checks for patch audability
- grid layout manager

There are probably a few improvements I could make here and there but this basically does what I want which is to decompile 90%+ of the patches in my favourite tracks, so I'm probably going to leave it there and start doing actual stuff with it now. 

Feel free to integrate this the way you want. My main takeaways

- importance of Note.clone() which is missing from RV - is absolutely vital here as a single note can belong to multiple patches, and often (usually) has different module references in each patch
- sample serialisation error, as added to issues - would be great to get that one fixed (I have no idea how)

Rgds -


```
 python rv/tools/patch_decompiler.py ~/packages/sunvox/examples/NightRadio\ -\ City\ Dreams.sunvox 
WARNING - Gen-Loo-Del-Dis/0 is inaudible
WARNING - Gen-Loo-Del-Dis/32 is inaudible
WARNING - Gen-Loo-Del-Dis/64 is inaudible
WARNING - Gen-Loo-Del-Dis/96 is inaudible
WARNING - Gen-LFO-Fla-Ech/1984 is inaudible
WARNING - Gen-LFO-Fla-Ech/2112 is inaudible
INFO - dumping 11 patches [48 versions] to tmp/NightRadio - City Dreams
```

**Comment by gldnspud** [comment]
Rebased this against latest commit in master.

**Comment by gldnspud** [comment]
There are some build errors that need to be fixed. I'll work on those while I review this.

**Comment by jhw** [comment]
Any news on this one ?

**Comment by gldnspud** [comment]
I had some personal and work stuff come up, sorry. I'll try to look at this over the coming weekend.

**Comment by gldnspud** [comment]
@jhw finally got a chance to play around with this.

What a brilliant tool! This is sort of thing that I was hoping Radiant Voices would be used for!

Someday, it would be nice to put some more polish onto the Solar Sails project (GUI tools to run alongside SunVox) and include a GUI for this patch decompiler.

I pushed a bunch of code styling, and although in an ideal world I'd like to do a little bit more in terms of adding some docs, I say... SHIP IT!  😄 

(In other words, if you are OK with the changes I made, go ahead and merge.)

**Comment by gldnspud** [comment]
A future idea, which we can do in a separate PR... would be to add a `--metamodule` option to the decompiler so it would output `.sunsynth` files that had the projects loaded, timeline playback turned on, and TPL/BPM set to whatever the source project was.

**Comment by gldnspud** [comment]
Another thing I noticed (for future ref), is that global commands that happen to repeat are not carried over into the deconstructions. It might be useful to add that functionality in the future.

For example, in one of my tracks I have a global shuffle by affecting the TPL. In the deconstructed version, the rhythms don't sound the same because of the lack of global shuffle.

**Comment by jhw** [comment]
Glad you like it, yes I think is useful. By all means merge it, I look
forward to using the merged version. Yes it could be improved in many ways
- global variables, sunsynths, do more than just straight line module
chains. Best merge this initial version and then maybe we can look at some
of those. I think the layout manager could be improved and simplified also,
probably should be part of a separate package. I have something else I am
working on (rv related) which I think you'll find interesting, I'll try and
create a branch / merge request in the upcoming week

**Comment by jhw** [comment]
I only tested it on the tracks I like :-) so there are probably lots of
edge cases such as the one u mention above that are not currently handled.
Suggest we create feature branches to fix as we come across them, try add
make the tool coverage more compete

**Pull request merged**
